@startuml
title Блок-схема методу Ейткена

start

:Ввід X, Y, n, x0;
:k1 := 0;

repeat
  :i := i + 1;
repeat while (i <= n - 2?) is (так)
->ні;

:i := 0;

while (i <= n - 2?) is (так)
  if ((x0 >= X[i]) and\n(x0 < X[i + 1])?) then (так)
    :k1 := i;
    break
  else (ні)
    :i := i + 1;
  endif
endwhile (ні)

:k := k1;
:res1 := 999;

while (k <= n - 2?) is (так)
  :j := 0;
  :i := k;

  while (i <= k1?) is (так)
    if (j = 0?) then (так)
      :A[i,j] := (((x0 - X[i]) * Y[i + 1])\n- ((x0 - X[i + 1]) * Y[i]))\n/ (X[i + 1] - X[i]);
    else (ні)
      :A[i,j] := (((x0 - X[i]) * A[i + 1, j])\n- ((x0 - X[i + j + 1]) * A[i, j]))\n/ (X[i + j + 1] - X[i]);
    endif

    :j := j + 1;
    :i := i + 1;
  endwhile (ні)

  :res2 := Abs(A[k1, j - 2] - A[k1, j - 1]);

  if (res2 < res1?) then (так)
    :res1 := res2;
  else (ні)
    :res := A[k1, j - 2];
    break
  endif

  :k := k + 1;
endwhile (ні)

:Вивід res;

stop
@enduml