plugins {
    id 'java'
    id 'application'
}

group = 'ua.artem'

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

repositories { mavenCentral() }

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
}

application {
    mainClass = 'ua.artem.Main'
}

tasks.jar {
    archiveBaseName = 'project2'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest { attributes 'Main-Class': application.mainClass }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
